# level script example
#	Commands:
#		spawn - spawns an entity
#		Parameters:
#			time - spawn time in milliseconds of game time
#			entity - id of entity to spawn
#			x - x coordinates
#			y - y coordinates
#			count - number of entities to spawn
#			delay - delay between each spawned entity
#			path - path to follow of each entity (see entity data)
#			pattern - bullet pattern to follow of each entity (see entity data)
spawn 100 grunt1 200 50 1 750 0 0
spawn 100 grunt1 600 50 1 750 1 0